### ISSUE TITLE
About guidelines

### ISSUE THREAD

**Issue by peritpatrio** [koodiklinikka/koodiklinikka.fi#9]
I think there should be some more guidelines about how the koodiklinikka.fi code should be structured so when people commit to the project they don't just do it in their own style.

**CSS for example**

If you take a look at https://github.com/koodiklinikka/koodiklinikka.fi/blob/master/src/styles/style.styl, you'll see that things aren't that organized yet (unrelated styling, different takes on selectors). :)

I personally prefer the [BEM(ish)-syntax](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) as well as avoiding element selectors, ids and nesting of selectors.

Recently I've started to sort the CSS properties alphabetically (with few exceptions) as it makes it easier to find the property you're looking for. Some exceptions are nice though, for example:

```css
/* Top, right etc.  are all related to the position property => group em! */
.foo {
  position: absolute;
    top: 0; right: 0; bottom: 0; left: 0;
}
```

If the site's code is structured neatly and follow some defined guidelines it would act as a good example for Koodiklinikka's beginners.

Any ideas/comments?
